[package]
name = "nadheer_chatharoo"
version = "0.1.0"
edition = "2021"

[dependencies]
pulldown-cmark = "0.12.2"
serde_json = "1.0.133"
serde = { version = "1.0.216", features = ["derive"] }
serde_yml = "0.0.12"
tera = "1.20.0"
walkdir = "2.5.0"
chrono = "0.4.39"